---
abstract: 'Verify BrowserID assertions.'
author:
  - 'Andrew Chilton <andychilton@gmail.com>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.132140'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-BrowserID-Verify
requires:
  Carp: 0
  Exporter: 0
  HTTP::Request::Common: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  Mouse: 0
resources:
  homepage: https://github.com/chilts/Net-BrowserID-Verify
  repository: git://github.com/chilts/Net-BrowserID-Verify.git
version: 0.002
